apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-busynginx-busybox-first
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.6.3
    chart: fluentd
    helm:
      valueFiles:
      - $values/deployments/infra/busynginx/busybox/first/values.yaml
  - repoURL: https://github.com/satyam-01-byte/argocd-test-2.git
    targetRevision: HEAD
    ref: values
    