apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  namespace: infra
  labels:
    app: selenium-chrome-node-service
spec:
  ports:
  - port: 5555
    protocol: TCP
  selector:
    app: selenium-chrome-hub
