apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-busynginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/staging/busynginx
    repoURL: https://github.com/satyam-01-byte/argocd-test-2.git
    targetRevision: HEAD