image:
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    memory: 50.0Mi
    cpu: 1.0
  requests:
    memory: 50.0Mi
    cpu: 1.0

fullnameOverride: nginx-test-2
namespaceOverride: infra

commonLabels: 
  app.kubernetes.io/name: nginx-test-2-beta  

nodeSelector:
  app.kubernetes.io/name: nginx-test-2

# podLabels:
#   app.kubernetes.io/name: nginx-test-2
