image:
  repository: bitnami/nginx
  tag: latest
  pullPolicy: Always

resources:
  limits:
    memory: 50.0Mi
    cpu: 1.0
  requests:
    memory: 50.0Mi
    cpu: 1.0

nameOverride: nginx-test-1
namespaceOverride: infra

labels: 
  app.kubernetes.io/name: nginx-test-1  

nodeSelector:
  app.kubernetes.io/name: nginx-test-1

podLabels:
  app.kubernetes.io/name: nginx-test-1