image:
  pullPolicy: Always

# replicaCount: 1

resources:
  limits:
    memory: 50.0Mi
    cpu: 0.1
  requests:
    memory: 50.0Mi
    cpu: 0.1

fullnameOverride: nginx-test-1
namespaceOverride: infra

commonLabels: 
  app.kubernetes.io/name: nginx-test-1  

nodeSelector:
  app.kubernetes.io/name: nginx-test-1

# podLabels:
#   app.kubernetes.io/name: nginx-test-1
