apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-busynginx-nginx-first
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.8.1
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets
      valueFiles:
      - values.yaml
      path: deployments/infra/busynginx/nginx/first
      repoURL: https://github.com/satyam-01-byte/argocd-test-2.git
      targetRevision: HEAD
      ref: values
    